#!/bin/bash

function prep() {
	name=$1
	perl join_strings.pl  tests/${name}.expected.cpp > tests/${name}.expected.cpp.new && mv tests/${name}.expected.cpp{.new,}
	perl -pe 's:\\":\\x22:g' -i tests/${name}.expected.cpp
      	indent -ut -kr tests/${name}.expected.cpp
	echo "$name: prepared";
}

for f in tests/*.tmpl; do
	name=$(basename "$f" .tmpl)
	if [ ! -f tests/${name}.expected.cpp -o tests/${name}.tmpl -nt tests/${name}.expected.cpp ] || [ -f tests/${name}.args -a tests/${name}.args -nt tests/${name}.expected.cpp ] ; then
		arguments=""
		if [ -f tests/${name}.args ]; then 
			arguments=$(cat tests/${name}.args);
		fi
		cppcms_tmpl_cc $arguments -o tests/${name}.expected.cpp $f 
		prep $name
	else
		echo "$name: skipped"
	fi
done

cppcms_tmpl_cc -o tests/tutorial-2.expected.cpp tests/tutorial-2*.tmpl-x
prep "tutorial-2"
