#!/bin/bash

for f in tests/*.tmpl; do
	name=$(basename "$f" .tmpl)
	if [ ! -f tests/${name}.expected.cpp ]; then
		arguments=""
		if [ -f tests/${name}.args ]; then 
			arguments=$(cat tests/${name}.args);
		fi
		cppcms_tmpl_cc $arguments -o tests/${name}.expected.cpp $f 
		perl -e 'local $/ = undef; local $string = <>; while($string =~ m/".+?"\s+"/) { $string =~ s:(".+?)"\s+":$1:gsm; } print $string' tests/${name}.expected.cpp > tests/${name}.expected.cpp.new &&  mv tests/${name}.expected.cpp{.new,}
	       	indent -ut -kr tests/${name}.expected.cpp
		echo "$name: prepared";
	else
		echo "$name: skipped"
	fi
done
