#!/bin/bash

mkdir -p tmp;
for f in tests/*.tmpl; do
	name=$(basename "$f" .tmpl)
	if [ -f tests/${name}.expected.cpp ]; then
		arguments=""
		if [ -f tests/${name}.args ]; then 
			arguments=$(cat tests/${name}.args);
		fi
		./parser $f --code > tmp/${name}.cpp $arguments
		indent -ut -kr tmp/${name}.cpp
		if diff -au tests/${name}.expected.cpp tmp/${name}.cpp; then
			echo "$name: OK";
		else
			echo "$name: FAILED";
			exit
		fi
	else
		echo "$name: no .expected file found"
	fi
done

